### ISSUE TITLE
Adding new pages

### ISSUE THREAD

**Issue by NikolaasBender** [meshhq/golang-html-template-tutorial#2]
I tried to add an about page. I copied everything for second_view and changed it to about and I added about.html to my templates. Then when I compile the bindata and the program in general I run into the issue:
`panic: asset: Asset(templates/about.html): Asset templates/about.html not found

goroutine 1 [running]:
panic
        ../../../src/libgo/go/runtime/panic.go:554
github_com_meshhq_golang_html_template_tutorial_assets.MustAsset
        /home/nickbender/go/src/github.com/meshhq/golang-html-template-tutorial/assets/bindata.go:312
github_com_meshhq_golang_html_template_tutorial_assets.MustAssetString
        /home/nickbender/go/src/github.com/meshhq/golang-html-template-tutorial/assets/assets.go:5
main.main..init0
        /home/nickbender/go/src/SoftwareDevProject/golang_skunkworks/main.go:40`
any help is good help to me. thank you

**Comment by vasilzhigilei** [comment]
Having the same issue, if anybody has any clues. Even when relative path seems to work for some code right after, assets.MustAssetString just can't seem to find the html files.
